dist: trusty
sudo: false
language: go

go:
  - 1.x
  - 1.8

script: go test -v

services:
  - mysql

before_script:
  - export MYSQL_DSN="travis@tcp(127.0.0.1:3306)/test"

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'